name: CI/CD of my basic-nodejs-s1

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest 

    steps:

      - name: Clone code from github
        uses: actions/checkout@v4

      - name: list of files.
        run: ls

      - name: build docker image
        run: docker build -t basic-nodejs-s1-image:latest .
        
      - name: list of images
        run: docker images