name: CI/CD of my basic-nodejs-s1

on:
  push:
    branches: [ "main" ]

env:
  BUILD_NUMBER: ${{ github.run_number }}

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Clone code from GitHub
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t basic-nodejs-s1-image-extra:${{ env.BUILD_NUMBER }} .

      - name: Tag Docker image
        run: docker tag basic-nodejs-s1-image-extra:${{ env.BUILD_NUMBER }} ${{ secrets.DOCKERHUB_USERNAME }}/basic-nodejs-s1-image-extra:${{ env.BUILD_NUMBER }}

      - name: List Docker images
        run: docker images

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/basic-nodejs-s1-image-extra:${{ env.BUILD_NUMBER }}

  test:

    runs-on: ubuntu-latest

    needs: ["build-and-push"]

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/basic-nodejs-s1-image-extra:${{ env.BUILD_NUMBER }}

      - name: Run tests on Docker container
        run: docker run ${{ secrets.DOCKERHUB_USERNAME }}/basic-nodejs-s1-image-extra:${{ env.BUILD_NUMBER }} npm test

  deploy:

    runs-on: ubuntu-latest

    needs: ["test"]

    steps:

      - name: Connect to the VPS using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            sudo docker stop basic-nodejs-s1-container || true
            sudo docker rm basic-nodejs-s1-container || true
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/basic-nodejs-s1-image-extra:${{ env.BUILD_NUMBER }} || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/basic-nodejs-s1-image-extra:${{ env.BUILD_NUMBER }}
            sudo docker run --pull always -d -p 3001:3000 --name basic-nodejs-s1-container ${{ secrets.DOCKERHUB_USERNAME }}/basic-nodejs-s1-image-extra:${{ env.BUILD_NUMBER }}
